import "reflect-metadata";
export * as event from "./common/event";
export * as react from "./react";
export * as component from "./components";
export * as monaco from "./monaco/api";
export * from "./i18n";
export * from "./workbench";
export * from "./services";
export * from "./model";
export { Controller } from "./react/controller";
export * from "./common/types";
